name: Push

'on':
  push:
    branches:
      - dev
      - master

defaults:
  run:
    shell: bash

jobs:
  ci:
    name: "CI (Push)"
    uses: ./.github/workflows/ci.yml
    with:
      os: "3.13"
      python-version: ubuntu-latest
